import { NextResponse } from 'next/server';
import { readFile } from 'fs/promises';
import { join } from 'path';

// Amazon-style product catalog (matching backend)
const CATALOG = [
  {
    id: "echo-dot-5",
    name: "Echo Dot (5th Gen)",
    description: "Smart speaker with Alexa - Charcoal",
    price: 4499,
    currency: "INR",
    category: "electronics",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Echo+Dot",
    rating: 4.5,
    reviews: 12500,
  },
  {
    id: "kindle-paperwhite",
    name: "Kindle Paperwhite",
    description: "8 GB - Now with a 6.8\" display and adjustable warm light",
    price: 13999,
    currency: "INR",
    category: "electronics",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Kindle",
    rating: 4.6,
    reviews: 8900,
  },
  {
    id: "fire-tv-stick",
    name: "Fire TV Stick 4K",
    description: "Streaming device with Alexa Voice Remote",
    price: 4999,
    currency: "INR",
    category: "electronics",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Fire+TV",
    rating: 4.4,
    reviews: 15200,
  },
  {
    id: "echo-show-8",
    name: "Echo Show 8",
    description: "HD smart display with Alexa - Charcoal",
    price: 8999,
    currency: "INR",
    category: "electronics",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Echo+Show",
    rating: 4.5,
    reviews: 11200,
  },
  {
    id: "ring-doorbell",
    name: "Ring Video Doorbell",
    description: "1080p HD video, motion detection, two-way talk",
    price: 9999,
    currency: "INR",
    category: "home-security",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Ring+Doorbell",
    rating: 4.3,
    reviews: 7800,
  },
  {
    id: "alexa-smart-plug",
    name: "TP-Link Smart Plug",
    description: "Works with Alexa - Control your home from anywhere",
    price: 999,
    currency: "INR",
    category: "smart-home",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Smart+Plug",
    rating: 4.2,
    reviews: 5600,
  },
  {
    id: "blink-outdoor",
    name: "Blink Outdoor Camera",
    description: "Wireless security camera with two-year battery life",
    price: 7999,
    currency: "INR",
    category: "home-security",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Camera",
    rating: 4.1,
    reviews: 4200,
  },
  {
    id: "roku-express",
    name: "Roku Express 4K+",
    description: "Streaming media player with voice remote",
    price: 3999,
    currency: "INR",
    category: "electronics",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Fire+TV",
    rating: 4.3,
    reviews: 9800,
  },
  {
    id: "fire-tv-cube",
    name: "Fire TV Cube",
    description: "4K Ultra HD streaming media player with hands-free Alexa",
    price: 12999,
    currency: "INR",
    category: "electronics",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Fire+TV",
    rating: 4.5,
    reviews: 9100,
  },
  {
    id: "ring-floodlight",
    name: "Ring Floodlight Cam Wired Pro",
    description: "1080p HD security camera with motion-activated LED floodlights",
    price: 18999,
    currency: "INR",
    category: "home-security",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Camera",
    rating: 4.4,
    reviews: 2900,
  },
  {
    id: "blink-mini",
    name: "Blink Mini Camera",
    description: "Compact indoor plug-in smart security camera with motion detection",
    price: 2999,
    currency: "INR",
    category: "home-security",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Camera",
    rating: 4.2,
    reviews: 15600,
  },
  {
    id: "philips-hue",
    name: "Philips Hue White and Color Ambiance",
    description: "Smart LED light bulb with 16 million colors, works with Alexa",
    price: 5499,
    currency: "INR",
    category: "smart-home",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Philips+Hue",
    rating: 4.6,
    reviews: 12300,
  },
  {
    id: "smart-lock",
    name: "August Smart Lock Pro",
    description: "Wi-Fi enabled smart lock with Alexa and Google Assistant support",
    price: 19999,
    currency: "INR",
    category: "smart-home",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Smart+Plug",
    rating: 4.3,
    reviews: 2100,
  },
  {
    id: "nest-thermostat",
    name: "Google Nest Learning Thermostat",
    description: "3rd Gen smart thermostat that learns your schedule and saves energy",
    price: 15999,
    currency: "INR",
    category: "smart-home",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Smart+Plug",
    rating: 4.5,
    reviews: 4500,
  },
  {
    id: "echo-buds",
    name: "Echo Buds (2nd Gen)",
    description: "True wireless earbuds with active noise cancellation and Alexa",
    price: 8999,
    currency: "INR",
    category: "electronics",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Echo+Buds",
    rating: 4.4,
    reviews: 8700,
  },
  {
    id: "echo-show-10",
    name: "Echo Show 10 (3rd Gen)",
    description: "10.1\" HD smart display with motion - Charcoal",
    price: 24999,
    currency: "INR",
    category: "electronics",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Echo+Show",
    rating: 4.6,
    reviews: 6800,
  },
  {
    id: "echo-studio",
    name: "Echo Studio",
    description: "High-fidelity smart speaker with 3D audio and Alexa",
    price: 22999,
    currency: "INR",
    category: "electronics",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Echo+Studio",
    rating: 4.7,
    reviews: 5200,
  },
  {
    id: "kindle-oasis",
    name: "Kindle Oasis",
    description: "32 GB - Premium e-reader with 7\" display and page turn buttons",
    price: 27999,
    currency: "INR",
    category: "electronics",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Kindle",
    rating: 4.8,
    reviews: 3400,
  },
  {
    id: "fire-tablet",
    name: "Fire HD 10 Tablet",
    description: "10.1\" 1080p Full HD display, 32 GB, Black",
    price: 12499,
    currency: "INR",
    category: "electronics",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Fire+Tablet",
    rating: 4.3,
    reviews: 18900,
  },
  {
    id: "ring-alarm",
    name: "Ring Alarm 8-Piece Kit",
    description: "Home security system with motion detector, contact sensor, and base station",
    price: 24999,
    currency: "INR",
    category: "home-security",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Camera",
    rating: 4.5,
    reviews: 3200,
  },
  {
    id: "wyze-cam",
    name: "Wyze Cam v3",
    description: "1080p HD indoor/outdoor security camera with color night vision",
    price: 3499,
    currency: "INR",
    category: "home-security",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Camera",
    rating: 4.4,
    reviews: 22100,
  },
  {
    id: "smart-switch",
    name: "TP-Link Kasa Smart Wi-Fi Light Switch",
    description: "Works with Alexa and Google Assistant, no hub required",
    price: 1999,
    currency: "INR",
    category: "smart-home",
    image_url: "https://via.placeholder.com/300x300/232F3E/FFFFFF?text=Smart+Plug",
    rating: 4.5,
    reviews: 13400,
  },
];

export async function GET() {
  try {
    // Return the catalog
    return NextResponse.json(CATALOG);
  } catch (error) {
    console.error('Error fetching products:', error);
    return NextResponse.json(
      { error: 'Failed to fetch products' },
      { status: 500 }
    );
  }
}

